ibm-apic-instance:
  ibmapicinstance:
    name: apic-cluster
    spec:
      license:
        accept: true
        use: production
        license: L-RJON-BZEP9N
      version: 10.0.5.5-6227
      profile: n3xc14.m48