ibm-apic-instance:
  ibmapicinstance:
    name: apic-cluster
    spec:
      license:
        accept: true
        use: production
        license: L-MMBZ-295QZQ
      version: 10.0.7.0-5560
      profile: n3xc14.m48
